# Generated by Django 4.0 on 2022-01-03 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('lower_non_recoverable', models.FloatField(blank=True, null=True)),
                ('lower_critical', models.FloatField(blank=True, null=True)),
                ('lower_non_critical', models.FloatField(blank=True, null=True)),
                ('upper_non_critical', models.FloatField(blank=True, null=True)),
                ('upper_critical', models.FloatField(blank=True, null=True)),
                ('upper_non_recoverable', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
